config/routes.rb
Rails.application.routes.draw do
  # devise routes
  devise_for :users

  # course_module routes
  resources :course_modules do
    resources :comments, only: [:create]
  end

  # users routes
  resources :users, only: [:index, :show, :edit, :update]

  # users search
  get 'search', to: "users#search"

  # home routes
  get 'home/index'

  # root path route ("/")
  root to: "home#index"

end

app/models/course_module.rb
class CourseModule < ApplicationRecord
  # model associations
  has_many :comments, dependent: :destroy
end

app/controllers/course_modules_controller.rb
class CourseModulesController < ApplicationController

  before_action :set_course_module, only: %i[ show edit update destroy ]

  # OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
  # SECURE - CanCanCan method - checks authorization config before every action
  load_and_authorize_resource

  # OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
  # SECURE - user must authenticate before specified actions
  before_action :authenticate_user!, only: %i[ edit update destroy ]

  # GET /course_modules or /course_modules.json
  def index
    @course_modules = CourseModule.all
  end

  # GET /course_modules/1 or /course_modules/1.json
  def show
  end

  # GET /course_modules/new
  def new
    @course_module = CourseModule.new
  end

  # GET /course_modules/1/edit
  def edit
  end

  # POST /course_modules or /course_modules.json
  def create
    @course_module = CourseModule.new(course_module_params)

    respond_to do |format|
      if @course_module.save
        format.html { redirect_to course_module_url(@course_module), notice: "Course module was successfully created." }
        format.json { render :show, status: :created, location: @course_module }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /course_modules/1 or /course_modules/1.json
  def update
    respond_to do |format|
      if @course_module.update(course_module_params)
        format.html { redirect_to course_module_url(@course_module), notice: "Course module was successfully updated." }
        format.json { render :show, status: :ok, location: @course_module }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course_module.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /course_modules/1 or /course_modules/1.json
  def destroy
    @course_module.destroy

    respond_to do |format|
      format.html { redirect_to course_modules_url, notice: "Course module was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course_module
      @course_module = CourseModule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_module_params
      params.require(:course_module).permit(:title, :code, :course, :year, :mode, :level, :lecturer, :description,
                                            :department)
    end
end

app/helpers/course_modules_helper.rb
module CourseModulesHelper
end

app/views/course_modules/_course_module.html.erb
<!--OWASP A03:2021 – Injection - https://owasp.org/Top10/A03_2021-Injection/
SECURE - removed raw helper tags when printing comment text to make the app less vulnerable to
XSS (Cross Site Scripting) attacks-->
<tr>
  <td><%= link_to course_module.title, course_module %></td>
  <td><%= course_module.code %></td>
  <td><%= course_module.course %></td>
  <td><%= course_module.year %></td>
  <td><%= course_module.mode %></td>
  <td><%= course_module.level %></td>
  <td><%= course_module.lecturer %></td>
  <td><%= course_module.description %></td>
  <td><%= course_module.department %></td>
</tr>

app/views/course_modules/_form.html.erb
<!--form template for creating or updating course module-->
<%= form_with(model: course_module) do |form| %>
  <% if course_module.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course_module.errors.count, "error") %> prohibited this course_module from being saved:</h2>

      <ul>
        <% course_module.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :course, style: "display: block" %>
    <%= form.text_field :course %>
  </div>

  <div>
    <%= form.label :year, style: "display: block" %>
    <%= form.number_field :year %>
  </div>

  <div>
    <%= form.label :mode, style: "display: block" %>
    <%= form.text_field :mode %>
  </div>

  <div>
    <%= form.label :level, style: "display: block" %>
    <%= form.text_field :level %>
  </div>

  <div>
    <%= form.label :lecturer, style: "display: block" %>
    <%= form.text_field :lecturer %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :department, style: "display: block" %>
    <%= form.text_field :department %>
  </div>

  <div class="p-1 m-1">
    <%= form.submit :class => "btn btn-primary btn-sm" %>
  </div>
<% end %>

app/views/course_modules/_table_headers.html.erb
<!--course module details table headers-->
<thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Code</th>
    <th scope="col">Course</th>
    <th scope="col">Year</th>
    <th scope="col">Mode</th>
    <th scope="col">Level</th>
    <th scope="col">Lecturer</th>
    <th scope="col">Description</th>
    <th scope="col">Department</th>
  </tr>
</thead>

app/views/course_modules/edit.html.erb
<!--course module edit page template-->
<h1>Editing course module</h1>

<!--render edit form template-->
<%= render "form", course_module: @course_module %>

<br>

<!--links-->
<div>
  <%= link_to "Show this course module", @course_module %> |
  <%= link_to "Back to course modules", course_modules_path %>
</div>

app/views/course_modules/index.html.erb
<!--course module index page template-->
<h1 class="p-3 m-3">Course Modules</h1>

<!--OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
SECURE - only logged in admin users can view create new course module button-->
<% if current_user && current_user.admin? %>
  <%= link_to "Add New Course Module", new_course_module_path, :class => "m-2 btn btn-success btn-sm" %>
<% end %>

<!--render course module details table-->
<table class="table table-hover table-striped">
  <!--render table headers template-->
  <%= render :partial => 'course_modules/table_headers' %>
  <tbody>
  <!--render table rows template and data-->
  <%= render @course_modules %>
  </tbody>
</table>

app/views/course_modules/new.html.erb
<!--new course module page-->
<h1 class="p-3 m-3">New course module</h1>

<!--render new course module form template-->
<%= render "form", course_module: @course_module %>

<br>

<!--links-->
<div>
  <%= link_to "Back to course modules", course_modules_path, :class => "btn btn-secondary btn-sm" %>
</div>

app/views/course_modules/show.html.erb
<!--course module show page template-->
<h1 class="p-3 m-3"><%= @course_module.title %> (<%= @course_module.code %>)</h1>

<!--print course module details-->
<table class="table table-hover table-striped">
  <!--render table headers-->
  <%= render :partial => 'course_modules/table_headers' %>
  <tbody>
  <!--render table rows and data-->
  <%= render @course_module %>
  </tbody>
</table>

<!--OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
SECURE - edit delete and add buttons should only be visible to admins-->
<% if current_user && current_user.admin? %>
  <div>
    <%= link_to "Edit Course Module", edit_course_module_path(@course_module), :class => "m-2 btn btn-primary btn-sm"%>
    <%= button_to "Delete Course Module", @course_module, method: :delete, :class => "m-2 btn btn-danger btn-sm" %>
    <%= link_to "New Course Module", new_course_module_path, :class => "m-2 btn btn-success btn-sm" %>
  </div>
<% end %>

<!--back to course modules page link-->
<div>
  <%= link_to "Back to Course Module", course_modules_path, :class => "m-2 btn btn-secondary btn-sm"  %>
</div>

<hr />

<!--OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
SECURE - only logged in users can view course module comments -->
<% if current_user %>
  <!--comments section-->
  <div class="row d-flex justify-content-center">
    <h3 class="p-3 m-3">Comments Section</h3>
    <!--print course_module comments using comments partial-->
    <%= render @course_module.comments %>
    <!--display new comments form using comments form partial-->
    <%= render partial: 'comments/form', locals: { course_module: @course_module }  %>
  </div>
<% end %>