config/routes.rb
Rails.application.routes.draw do
  # devise routes
  devise_for :users

  # course_module routes
  resources :course_modules do
    resources :comments, only: [:create]
  end

  # users routes
  resources :users, only: [:index, :show, :edit, :update]

  # users search
  get 'search', to: "users#search"

  # home routes
  get 'home/index'

  # root path route ("/")
  root to: "home#index"

end

app/models/comment.rb
class Comment < ApplicationRecord
  # model associations
  belongs_to :course_module
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # @Ref: https://www.youtube.com/watch?v=TcltF0KVyrE
  # Ref description: tutorial on how to add comments to a resource

  # skip authenticity token before executing any action
  skip_before_action :verify_authenticity_token

  # before executing any action for this controller authenticate user
  before_action :authenticate_user!

  # create comment action
  def create
    @comment = current_user.comments.new(comment_params)
    if !@comment.save
      flash[:notice] = @comment.errors.full_messages.to_sentence
    end

    # redirect to course module path
    redirect_to course_module_path(params[:course_module_id])
  end

  private

  # params required for creating new comment
  def comment_params
    params
      .require(:comment)
      .permit(:content)
      .merge(course_module_id: params[:course_module_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!--@Ref: https://www.youtube.com/watch?v=TcltF0KVyrE
Ref description: tutorial on how to add comments to a resource-->

<!--template for printing each comment-->
<div class="card mb-4 bg-light border border-dark">
  <article>

    <!--OWASP A03:2021 – Injection - https://owasp.org/Top10/A03_2021-Injection/
    SECURE - removing raw helper tag when printing comment text makes the app less vulnerable to
    XSS (Cross Site Scripting) attacks-->
    <p><%= comment.content %></p>

    <!-- print comment author -->
    <small>Created by <%= comment.user.try(:email) %> </small>

    <!-- print comment created date time -->
    <small>on <%= comment.created_at.strftime("%d/%m/%Y at %H:%M") %></small>

  </article>
</div>

app/views/comments/_form.html.erb
<!--@Ref: https://www.youtube.com/watch?v=TcltF0KVyrE
Ref description: tutorial on how to add comments to a resource-->

<!--form for creating new comment-->
<div class="card mb-4 bg-secondary">
  <form action="<%= course_module_comments_path(course_module) %>" method="post">
    <!--<input type="hidden" name="authenticity_token">-->

    <!--form label-->
    <label for="comment" class="form-label text-white">Create New Comment:</label>

    <!--text area for adding new comment text-->
    <textarea class="form-control form-control-sm" id="comment" name="comment[content]" rows="6" cols="50" ></textarea>

    <br>
    <!--submit button-->
    <input type="submit" value="Post Comment" class="m-2 btn btn-primary">
  </form>
</div>