config/routes.rb
Rails.application.routes.draw do
  # devise routes
  devise_for :users

  # course_module routes
  resources :course_modules do
    resources :comments, only: [:create]
  end

  # users routes
  resources :users, only: [:index, :show, :edit, :update]

  # users search
  get 'search', to: "users#search"

  # home routes
  get 'home/index'

  # root path route ("/")
  root to: "home#index"

end

app/models/user.rb
class User < ApplicationRecord

  # devise settings
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :timeoutable, :encryptable

  # user comment relationship
  has_many :comments, dependent: :destroy

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
  # SECURE - CanCanCan method - checks authorization config before every action
  load_and_authorize_resource

  # OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
  # SECURE - user must authenticate before executing controller actions
  before_action :authenticate_user!

  # index action
  def index
    @users = User.all
  end

  # show action
  def show
    if current_user.admin?
      @user = User.find(params[:id])
    else
      @user = User.find(params[:id])
      if current_user != @user
        redirect_to root_path, notice: "Sorry, but you are only allowed to view your own profile page."
      end
    end
  end

  # edit action
  def edit
    # OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
    # SECURE - edit page user ID is set to currently logged in users ID
    if current_user.admin?
      @user = User.find(params[:id])
    else
      @user = User.find(params[:id])
      if current_user != @user
        redirect_to root_path, notice: "Sorry, but you are only allowed to edit your own profile page."
      end
    end
  end

  # update action
  def update
    # OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
    # SECURE - current user can only update their own account details
    if current_user.admin?
      @user = User.find(params[:id])
      @user.update(user_params)
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'You successfully updated your profile.' }
        else
          format.html { render :edit }
        end
      end
    else
      @user = User.find(params[:id])
      if current_user != @user
        redirect_to root_path, notice: "Sorry, but you are only allowed to update your own profile page."
      end
      respond_to do |format|
        if current_user.update(user_params)
          format.html { redirect_to current_user, notice: 'You successfully updated your profile.' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  # @Ref: https://www.youtube.com/watch?v=s88Uc0InOAM
  # Ref description: tutorial on how to add search functionality for a resource
  # users search action
  def search
    # OWASP A03:2021 – Injection - https://owasp.org/Top10/A03_2021-Injection/
    # SECURE - user search input is sanitized to mitigate the risk of SQL injection attacks
    @users = User.where('email LIKE ?', "%#{ActiveRecord::Base.sanitize_sql_like(params[:q])}%")
  end

  private

  # user update parameters
  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :dob,
      :pps_number,
      :address,
      :contact_number,
      :emergency_contact_name,
      :emergency_contact_number
    )
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<!--user update form-->
<%= form_with(model: user, local: true) do |form| %>

    <!--  print any user update errors -->
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(user.errors.count, "error") %>
          prohibited this user from being saved:
        </h2>

        <ul>
          <% user.errors.full_messages.each do |message| %>
            <li>
              <%= message %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <!-- first name form text field -->
    <div class="form-group">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>

    <!-- last name form text field -->
    <div class="form-group">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>

    <!-- dob form text field -->
    <div class="form-group">
      <%= form.label :dob %>
      <%= form.text_field :dob, class: 'form-control' %>
    </div>

    <!-- pps form text field -->
    <div class="form-group">
      <%= form.label :pps_number %>
      <%= form.text_field :pps_number, class: 'form-control' %>
    </div>

    <!-- address form text field -->
    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_field :address, class: 'form-control' %>
    </div>

    <!-- contact number form text field -->
    <div class="form-group">
      <%= form.label :contact_number %>
      <%= form.number_field :contact_number, class: 'form-control' %>
    </div>

    <!-- contact name form text field -->
    <div class="form-group">
      <%= form.label :emergency_contact_name %>
      <%= form.text_field :emergency_contact_name, class: 'form-control' %>
    </div>

    <!-- contact number form text field -->
    <div class="form-group">
      <%= form.label :emergency_contact_number %>
      <%= form.number_field :emergency_contact_number, class: 'form-control' %>
    </div>

    <br>

    <!-- form submit and cancel buttons -->
    <div class="form-group">
      <%= form.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', root_path, class: 'btn btn-secondary' %>
    </div>

  </div>
<% end %>

app/views/users/_table_headers.html.erb
<!--user details table headers-->
<thead>
  <tr>
    <th scope="col">ID</th>
    <th scope="col">Email</th>
    <th scope="col">Admin</th>
    <th scope="col">First Name</th>
    <th scope="col">Last Name</th>
    <th scope="col">Student No.</th>
    <th scope="col">Course</th>
    <th scope="col">Start Date</th>
    <th scope="col">DOB</th>
    <th scope="col">PPS No.</th>
    <th scope="col">Address</th>
    <th scope="col">Contact No.</th>
    <th scope="col">Emergency Contact</th>
    <th scope="col">Emergency Contact No.</th>
  </tr>
</thead>

app/views/users/_user.html.erb
<!--user details table rows template-->

<!--OWASP A03:2021 – Injection - https://owasp.org/Top10/A03_2021-Injection/
SECURE - removing raw helper tag makes the app less vulnerable to XSS (Cross Site Scripting) attacks-->
<tr>
  <td><%= user.id %></td>
  <td><%= link_to user.email, user %></td>
  <td><%= user.admin %></td>
  <td><%= user.first_name %></td>
  <td><%= user.last_name %></td>
  <td><%= user.student_number %></td>
  <td><%= user.course %></td>
  <td><%= user.course_started %></td>
  <td><%= user.dob %></td>
  <td><%= user.pps_number %></td>
  <td><%= user.address %></td>
  <td><%= user.contact_number %></td>
  <td><%= user.emergency_contact_name %></td>
  <td><%= user.emergency_contact_number %></td>
</tr>

app/views/users/edit.html.erb
<!--users edit page template-->
<h1>Edit User Details</h1>

<!--render user edit form-->
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<!--users index page template-->
<h1 class="p-3 m-3">Users</h1>

<table class="table table-hover table-striped">
  <!--render table headers template-->
  <%= render :partial => 'users/table_headers' %>
  <!--render table rows and data-->
  <tbody>
    <%= render @users %>
  </tbody>
</table>

app/views/users/search.erb
<!--@Ref: https://www.youtube.com/watch?v=s88Uc0InOAM
Ref description: tutorial on how to add search functionality for a resource-->
<!--search results template-->
<h1>Search Results</h1>

<!--OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
SECURE - only logged in admin users can view user search results-->
<% if current_user && current_user.admin? %>
  <!--if there are no search results display the following-->
  <% if @users.count == 0 %>
      <p>Sorry, no users matched your search query. Please try again </p>
  <!--else display the matching users-->
  <% else %>
      <span> <%= @users.count %> Users(s) Found: </span>
      <br>
      <!--print users details in table-->
      <table class="table table-hover table-striped">
          <%= render :partial => 'users/table_headers' %>
          <tbody>
          <%= render @users %>
          </tbody>
      </table>
  <% end %>
<% end %>

app/views/users/show.html.erb
<!--# OWASP A01:2021 – Broken Access Control - https://owasp.org/Top10/A01_2021-Broken_Access_Control/
# SECURE - users details page data only displays for current user if it is their user details page or they are
admins-->
<% if current_user.id == @user.id || current_user.admin? %>
  <!--user details show page-->
  <h1 class="m-3">User ID <%= @user.id %></h1>
  <h4>(<%= @user.email %>)</h4>

  <!--print users details in table-->
  <table class="table table-hover table-striped">
      <%= render :partial => 'users/table_headers' %>
    <tbody>
      <%= render @user %>
    </tbody>
  </table>


  <%= link_to 'Edit My Details', edit_user_path(current_user), class: 'btn btn-primary' %>

<% end %>