config/routes.rb
Rails.application.routes.draw do
  # devise routes
  devise_for :users

  # course_module routes
  resources :course_modules do
    resources :comments, only: [:create]
  end

  # users routes
  resources :users, only: [:index, :show, :edit, :update]

  # users search
  get 'search', to: "users#search"

  # home routes
  get 'home/index'

  # root path route ("/")
  root to: "home#index"

end

app/views/layouts/_alerts.html.erb
<!--@Ref: https://stackoverflow.com/questions/70972434/rails-7-bootstrap-alert-is-not-been-dismissed
Ref description - stack overflow question on how to display bootstrap 5 alerts in RoR-->
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<!--@REF: https://getbootstrap.com/docs/5.0/components/navbar/
Ref description: Bootstrap v5 navbar template-->

<!--navbar start-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <!--logo and app name with link to homepage-->
    <a class="navbar-brand" href="<%= root_path %>">

      <!--@REF: https://www.flaticon.com/free-icon/education_4207253?term=student&page=1&position=59&origin=
      search&related_id=4207253
      Ref Description: logo reference-->
      <%= image_tag "logo.png", :height => 24, :width => 30, :class => "d-inline-block align-text-top" %>
      Student Management System
    </a>

    <!--hamburger icon-->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!--navbar items-->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <!--course modules link-->
          <li class="nav-item">
            <a class="nav-link" href="<%= course_modules_path %>">Course Modules</a>
          </li>

        <% if user_signed_in? && current_user.admin? %>
          <!--course modules link-->
          <li class="nav-item">
            <a class="nav-link" href="<%= users_path %>">Users</a>
          </li>
        <% end %>

        <!--if the user is logged in show the following navbar items-->
        <% if user_signed_in? %>

          <!--user account link-->
          <li class="nav-item">
            <a class="nav-link" href="<%= user_path(current_user) %>">My Details</a>
          </li>

          <!--user account link-->
          <li class="nav-item">
            <a class="nav-link" href="<%= edit_user_registration_path %>">Account Settings</a>
          </li>

          <!--log out link-->
          <li class="nav-item">
            <a class="nav-link" href="<%= destroy_user_session_path %>">Log Out</a>
          </li>

        <% else %><!--if the user is logged out show the following navbar items-->
        <!--sign up link-->
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">Sign Up</a>
          </li>

          <!--log in link-->
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path %>">Login</a>
          </li>
        <% end %>

      </ul>

      <!--OWASP A07:2021 - https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/
      INSECURE - any user can search for users using the search bar-->
      <!--search bar-->
      <form action="/search" class="d-flex">
        <input class="form-control me-2" type="text" name="q" placeholder="Search for students" aria-label="Search for students">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <!--OWASP A07:2021 - https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/
      SECURE - any admin users can search for users using the search bar-->
      <!--search bar-->
<!--      <%# if current_user && current_user.admin? %>
        <form action="/search" class="d-flex">
          <input class="form-control me-2" type="text" name="q" placeholder="Search for students" aria-label="Search for students">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      <%# end %>-->

    </div>
  </div>
</nav>
<!--navbar end-->

app/views/layouts/application.html.erb
<!--application template-->
<!doctype html>
<html lang="en">
  <head>
    <!--application title-->
    <title>StudentManagementSystem</title>

    <!--meta tags-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%#= javascript_importmap_tags %>

    <!--bootstrap css (v.5)-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">

    <!--application css link-->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body class="d-flex flex-column h-100 text-center">
    <!--render navbar-->
    <%= render 'layouts/header' %>

    <!--render alerts if any-->
    <%= render 'layouts/alerts' %>

    <!--main content-->
    <main class="flex-shrink-0">
      <div class="container">
        <!--render current page content-->
        <%= yield %>
      </div>
    </main>

    <!--Javascript required for bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
  </body>
</html>